services:
  api:
    build: 
      context: .
      args:
        - STATIC_URL=/static/
    ports:
      - 8000:8000
    networks:
      - saleor-backend-tier
    depends_on:
      - db
      - redis
    volumes:
      - saleor-media:/app/media
    env_file:
      - .env
    command: ["gunicorn", "--bind", ":8000", "--workers", "4", "--worker-class", "saleor.asgi.gunicorn_worker.UvicornWorker", "saleor.asgi:application"]

  db:
    image: library/postgres:15-alpine
    ports:
      - 5432:5432
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: library/redis:7.0-alpine
    ports:
      - 6379:6379
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

volumes:
  saleor-db:
  saleor-redis:
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge